---

- name: Ensure gnugp is installed for importing keys
  apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - apt-transport-https
      - gnupg

- name: Add Nginx signing key
  shell: wget -qO - https://nginx.org/keys/nginx_signing.key | sudo apt-key add -
  args:
    warn: false
  when: ansible_distribution_major_version == "14"

- name: Add Nginx signing key
  apt_key:
    url: https://nginx.org/keys/nginx_signing.key
    state: present
  when: ansible_distribution_major_version != '14'

- name: Configure repository
  apt_repository:
    repo: "deb https://nginx.org/packages/{{ ansible_distribution |lower }}/ {{ ansible_distribution_release }} nginx"
    state: present
    filename: nginx_stable
    update_cache: yes

- name: Install Nginx
  apt:
    name: nginx
    state: present
  register: is_installed
  notify:
    - Enable and start Nginx
